purchasing/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''

import sys
import logging
import os
import datetime

from pkgutil import iter_modules
from importlib import import_module

from werkzeug.utils import import_string

from flask import Flask, render_template, Blueprint
from celery import Celery

from flask_login import current_user

from purchasing.assets import assets, test_assets
from purchasing.extensions import (
    bcrypt, cache, db, login_manager,
    migrate, debug_toolbar, admin, s3, mail
)

from purchasing.filters import (
    url_for_other_page, thispage, format_currency, better_title,
    days_from_today, datetimeformat, format_days_from_today,
    newline_to_br, localize, now, print_user_name, display_dedupe_array,
    external_link_warning
)

# import models so that flask-migrate can auto-detect
from purchasing.public.models import AppStatus

def log_file(app):
    log_dir = '/var/log/chime'
    if not os.access(log_dir, os.W_OK | os.X_OK):
        log_dir = app.config.get('LOG_PATH', app.config['PROJECT_ROOT'] + '/log')
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
    return os.path.join(os.path.realpath(log_dir), 'app.log')

def make_celery():
    config = os.environ['CONFIG']
    if isinstance(config, basestring):
        config = import_string(config)
    return Celery(__name__, broker=getattr(config, 'CELERY_BROKER_URL', 'sqla+postgresql://localhost/purchasing'))

celery = make_celery()

def create_app():
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config: A config object or import path to the config object string.
    '''
    config_string = os.environ['CONFIG']
    if isinstance(config_string, basestring):
        config = import_string(config_string)
    else:
        config = config_string
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    register_jinja_extensions(app)
    register_errorhandlers(app)

    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return TaskBase.__call__(self, *args, **kwargs)

    celery.Task = ContextTask

    @app.before_first_request
    def before_first_request():
        register_logging(app, config_string)

    return app

def register_extensions(app):
    test_assets.init_app(app) if app.config.get('TESTING') else assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    from purchasing.users.models import AnonymousUser
    login_manager.anonymous_user = AnonymousUser
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    admin.init_app(app)
    s3.init_app(app)
    mail.init_app(app)

    from flask_sslify import SSLify
    # only trigger SSLify if the app is running on Heroku
    if 'DYNO' in os.environ:
        SSLify(app)
    return None

def register_blueprints(app, package_name='purchasing', package_path=None):
    from purchasing.admin import views
    package_path = package_path if package_path else app.config['APP_DIR']
    rv = []
    for _, name, _ in iter_modules([package_path]):
        m_name = '{}.{}'.format(package_name, name)
        m = import_module(m_name)
        for item in dir(m):
            item = getattr(m, item)
            if isinstance(item, Blueprint):
                app.register_blueprint(item)
            rv.append(item)

    return rv

def register_jinja_extensions(app):
    app.jinja_env.globals['url_for_other_page'] = url_for_other_page
    app.jinja_env.globals['thispage'] = thispage
    app.jinja_env.globals['_current_user'] = current_user
    app.jinja_env.globals['today'] = datetime.date.today()
    app.jinja_env.globals['days_from_today'] = days_from_today
    app.jinja_env.globals['format_days_from_today'] = format_days_from_today
    app.jinja_env.globals['_now'] = now
    app.jinja_env.globals['external_link_warning'] = external_link_warning
    app.jinja_env.filters['print_user_name'] = print_user_name
    app.jinja_env.filters['currency'] = format_currency
    app.jinja_env.filters['title'] = better_title
    app.jinja_env.filters['datetimeformat'] = datetimeformat
    app.jinja_env.filters['localize'] = localize
    app.jinja_env.filters['newline_to_br'] = newline_to_br
    app.jinja_env.filters['display_dedupe_array'] = display_dedupe_array
    return None

def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)

        if error_code == 500:
            app_status = AppStatus.query.first()
            app_status.status = 'error'
            app_status.last_updated = datetime.datetime.utcnow()
            app_status.message = str(error)
            db.session.commit()

        app.logger.exception(error)

        return render_template("errors/{0}.html".format(error_code)), error_code
    for errcode in [401, 403, 404, 413, 500]:
        # for 500-level status codes, change the db status
        app.errorhandler(errcode)(render_error)
    return None

def register_logging(app, config_string):
    if 'prod' in config_string.lower():

        # for heroku, just send everything to the console (instead of a file)
        # and it will forward automatically to the logging service

        # disable the existing flask handler, we are replacing it with our own
        app.logger.removeHandler(app.logger.handlers[0])

        class UserEmailFilter(logging.Filter):
            '''
            This is a filter which injects contextual information into the log.
            '''
            def filter(self, record):
                user_id = current_user.email if not current_user.is_anonymous() else 'anonymous'
                record.user_id = user_id
                return True

        _filter = UserEmailFilter()

        app.logger.setLevel(logging.DEBUG)
        stdout = logging.StreamHandler(sys.stdout)
        stdout.setFormatter(logging.Formatter(
            '''--------------------------------------------------------------------------------
%(asctime)s | %(levelname)s in %(module)s [%(funcName)s] | %(user_id)s | [%(pathname)s:%(lineno)d] | %(message)s
--------------------------------------------------------------------------------'''
        ))
        app.logger.addFilter(_filter)
        app.logger.addHandler(stdout)

        # log to a file. this is commented out for heroku deploy, but kept
        # in case we need it later

        # file_handler = logging.handlers.RotatingFileHandler(log_file(app), 'a', 10000000, 10)
        # file_handler.setFormatter(logging.Formatter(
        #     '%(asctime)s | %(name)s | %(levelname)s in %(module)s [%(pathname)s:%(lineno)d]: %(message)s')
        # )
        # app.logger.addHandler(file_handler)
        # app.logger.setLevel(logging.DEBUG)

    elif 'test' in config_string.lower():
        app.logger.setLevel(logging.CRITICAL)

    else:
        # log to console for dev
        app.logger.setLevel(logging.DEBUG)

    return None

purchasing/conductor/__init__.py
# -*- coding: utf-8 -*-

from .manager import blueprint as mbp
from .metrics import blueprint as mebp
from .upload import blueprint as ubp

purchasing/conductor/manager/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'conductor', __name__, url_prefix='/conductor',
    template_folder='../templates'
)

from . import index, detail, complete, flow_management

purchasing/conductor/metrics/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'conductor_metrics', __name__, url_prefix='/conductor/metrics',
    template_folder='../templates'
)

from . import views

purchasing/conductor/views.py
# -*- coding: utf-8 -*-

import urllib2
import datetime
import os

from werkzeug import secure_filename

from flask import (
    Blueprint, render_template, flash, redirect,
    url_for, abort, request, jsonify, current_app
)
from flask_login import current_user
from sqlalchemy.exc import IntegrityError

from purchasing.decorators import requires_roles
from purchasing.database import db
from purchasing.notifications import new_contract_autoupdate, send_conductor_alert
from purchasing.data.stages import transition_stage
from purchasing.data.flows import create_contract_stages
from purchasing.data.models import (
    ContractBase, ContractProperty, ContractStage, Stage,
    ContractStageActionItem, Flow
)
from purchasing.data.importer.costars import main as import_costars
from purchasing.users.models import User, Role
from purchasing.conductor.forms import (
    EditContractForm, PostOpportunityForm,
    SendUpdateForm, NoteForm, FileUpload
)

blueprint = Blueprint(
    'conductor', __name__, url_prefix='/conductor',
    template_folder='../templates'
)

@blueprint.route('/')
@requires_roles('conductor', 'admin', 'superadmin')
def index():
    all_contracts, assigned_contracts = [], []

    contracts = db.session.query(
        ContractBase.id, ContractBase.description,
        ContractBase.financial_id, ContractBase.expiration_date,
        ContractBase.current_stage, Stage.name.label('stage_name'),
        ContractBase.updated_at, User.email.label('assigned'),
        ContractProperty.value.label('spec_number'),
        ContractBase.contract_href
    ).join(ContractProperty).outerjoin(Stage).outerjoin(User).filter(
        db.func.lower(ContractBase.contract_type) == 'county',
        ContractBase.expiration_date is not None,
        db.func.lower(ContractProperty.key) == 'spec number',
    ).order_by(ContractBase.expiration_date).all()

    conductors = User.query.join(Role).filter(
        Role.name == 'conductor',
        User.email != current_user.email
    ).all()

    user_starred = [] if current_user.is_anonymous() else current_user.get_starred()

    for contract in contracts:
        if contract.assigned:
            assigned_contracts.append(contract)
        else:
            all_contracts.append(contract)

    return render_template(
        'conductor/index.html',
        contracts=all_contracts,
        assigned=assigned_contracts,
        user_starred=user_starred,
        current_user=current_user,
        conductors=[current_user] + conductors,
        path='{path}?{query}'.format(
            path=request.path, query=request.query_string
        )
    )

@blueprint.route('/contract/<int:contract_id>', methods=['GET', 'POST'])
@blueprint.route('/contract/<int:contract_id>/stage/<int:stage_id>', methods=['GET', 'POST'])
@requires_roles('conductor', 'admin', 'superadmin')
def detail(contract_id, stage_id=-1):
    '''View to control an individual stage update process
    '''
    if request.args.get('transition'):

        clicked = int(request.args.get('destination')) if \
            request.args.get('destination') else None

        stage, mod_contract, complete = transition_stage(
            contract_id, destination=clicked, user=current_user
        )
        if complete:
            return redirect(url_for('conductor.edit', contract_id=mod_contract.id))

        return redirect(url_for(
            'conductor.detail', contract_id=contract_id, stage_id=stage.id
        ))

    if stage_id == -1:
        # redirect to the current stage page
        contract_stage = ContractStage.query.join(
            ContractBase, ContractBase.id == ContractStage.contract_id
        ).filter(
            ContractStage.contract_id == contract_id,
            ContractStage.stage_id == ContractBase.current_stage_id
        ).first()

        return redirect(url_for(
            'conductor.detail', contract_id=contract_id, stage_id=contract_stage.id
        ))

    stages = db.session.query(
        ContractStage.contract_id, ContractStage.stage_id, ContractStage.id,
        ContractStage.entered, ContractStage.exited, Stage.name,
        Stage.send_notifs, Stage.post_opportunities, ContractBase.description
    ).join(Stage, Stage.id == ContractStage.stage_id).join(
        ContractBase, ContractBase.id == ContractStage.contract_id
    ).filter(
        ContractStage.contract_id == contract_id
    ).order_by(ContractStage.id).all()

    try:
        active_stage = [i for i in stages if i.id == stage_id][0]
        current_stage = [i for i in stages if i.entered and not i.exited][0]
        if active_stage.entered is None:
            abort(404)
    except IndexError:
        abort(404)

    note_form = NoteForm()
    update_form = SendUpdateForm()
    opportunity_form = PostOpportunityForm()

    forms = {
        'activity': note_form, 'update': update_form, 'post': opportunity_form
    }

    active_tab = '#activity'
    submitted_form = request.args.get('form', None)
    if submitted_form:
        if handle_form(forms[submitted_form], submitted_form, stage_id, current_user):
            return redirect(url_for(
                'conductor.detail', contract_id=contract_id, stage_id=stage_id
            ))
        else:
            active_tab = '#' + submitted_form

    actions = ContractStageActionItem.query.filter(
        ContractStageActionItem.contract_stage_id == stage_id
    ).order_by(db.text('taken_at asc')).all()

    actions.extend([
        ContractStageActionItem(action_type='entered', action_detail=active_stage.entered, taken_at=active_stage.entered),
        ContractStageActionItem(action_type='exited', action_detail=active_stage.exited, taken_at=active_stage.exited)
    ])
    actions = sorted(actions, key=lambda stage: stage.get_sort_key())

    if len(stages) > 0:
        return render_template(
            'conductor/detail.html',
            stages=stages, actions=actions, active_tab=active_tab,
            note_form=note_form, update_form=update_form,
            opportunity_form=opportunity_form, contract_id=contract_id,
            current_user=current_user, active_stage=active_stage,
            current_stage=current_stage
        )
    abort(404)

def handle_form(form, form_name, stage_id, user):
    if form.validate_on_submit():
        action = ContractStageActionItem(
            contract_stage_id=stage_id, action_type=form_name,
            taken_by=user.id, taken_at=datetime.datetime.now()
        )
        if form_name == 'activity':
            action.action_detail = {'note': form.data.get('note', '')}

        elif form_name == 'update':
            action.action_detail = {
                'sent_to': form.data.get('send_to', ''),
                'body': form.data.get('body'),
                'subject': form.data.get('subject')
            }
            send_conductor_alert(
                form.data.get('send_to'), form.data.get('subject'),
                form.data.get('body'), current_user.email
            )

        elif form_name == 'opportunity':
            pass

        else:
            return False

        db.session.add(action)
        db.session.commit()
        return True

    return False

@blueprint.route('/contract/<int:contract_id>/stage/<int:stage_id>/note/<int:note_id>/delete', methods=['GET', 'POST'])
@requires_roles('conductor', 'admin', 'superadmin')
def delete_note(contract_id, stage_id, note_id):
    try:
        note = ContractStageActionItem.query.get(note_id)
        if note:
            note.delete()
            flash('Note deleted successfully!', 'alert-success')
        else:
            flash("That note doesn't exist!", 'alert-warning')
    except Exception, e:
        flash('Something went wrong: {}'.format(e.message), 'alert-danger')
    return redirect(url_for('conductor.detail', contract_id=contract_id, stage_id=stage_id))

@blueprint.route('/contract/<int:contract_id>/edit', methods=['GET', 'POST'])
@requires_roles('conductor', 'admin', 'superadmin')
def edit(contract_id):
    '''Update information about a contract
    '''
    contract = ContractBase.query.get(contract_id)

    if contract:
        spec_number = contract.get_spec_number()
        form = EditContractForm(obj=contract)

        if form.validate_on_submit():
            data = form.data
            new_spec = data.pop('spec_number', None)

            if new_spec:
                spec_number.key = 'Spec Number'
                spec_number.value = new_spec
                contract.properties.append(spec_number)

            contract.update(**data)
            flash('Contract Successfully Updated!', 'alert-success')
            new_contract_autoupdate(contract, current_user.email)

            return redirect(url_for('conductor.edit', contract_id=contract.id))

        form.spec_number.data = spec_number.value
        return render_template('conductor/edit.html', form=form, contract=contract)
    abort(404)

@blueprint.route('/contract/<int:contract_id>/edit/url-exists', methods=['POST'])
@requires_roles('conductor', 'admin', 'superadmin')
def url_exists(contract_id):
    '''Check to see if a url returns an actual page
    '''
    url = request.json.get('url', '')
    if url == '':
        return jsonify({'status': 404})

    req = urllib2.Request(url)
    request.get_method = lambda: 'HEAD'

    try:
        response = urllib2.urlopen(req)
        return jsonify({'status': response.getcode()})
    except urllib2.HTTPError, e:
        return jsonify({'status': e.getcode()})

@blueprint.route('/contract/<int:contract_id>/assign/<int:user_id>/flow/<int:flow_id>')
@requires_roles('conductor', 'admin', 'superadmin')
def assign(contract_id, flow_id, user_id):
    '''Assign a contract to an admin or a conductor
    '''
    contract = ContractBase.query.get(contract_id)
    flow = Flow.query.get(flow_id)

    if not flow:
        flash('Something went wrong! That flow doesn\'t exist!', 'alert-danger')
        return redirect('conductor.index')

    try:

purchasing/templates/macros/comma_separated_loop.html
{% macro comma_separated_loop(loop) %}
  {%- if loop.length == 2 -%}
    {%- if not loop.last %} and{%- endif -%}
  {%- elif loop.length > 2 -%}
    {%- if loop.index == loop.length - 1 -%}, and
    {%- elif not loop.last -%},
    {%- endif -%}
  {%- endif -%}
{% endmacro %}

purchasing/templates/macros/flash_messages.html
{% macro flash_messages() %}
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert {{ category }} alert-dismissible flashed-alert fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
  {% endwith %}
{% endmacro %}

purchasing/templates/macros/print_name.html
{% macro print_name(action, user) %}
  {%- if action.taken_by == user.id %}
    You
  {%- else %}
    {{ action.taken_by|print_user_name }}
  {%- endif %}
{% endmacro %}

purchasing/templates/macros/render_activity_log.html
{% import 'macros/print_name.html' as pn %}
{% import 'macros/comma_separated_loop.html' as csl %}
{% macro render_activity_log(action, current_user, contract, top_level, current_stage) %}

  {%- if action.action_type in ['activity', 'note'] -%}
  <div class="action-event js-filter-action-note">
    <span class="event-icon"><i class="fa fa-pencil"></i></span>
    {{ pn.print_name(action, current_user) }}
    wrote "<strong>{{ action.action_detail.note }}</strong>" on {{ action.taken_at|datetimeformat('%m/%d/%y') }}.

    {% if top_level %}
    <span class="pull-right">
      <a href="{{ url_for('conductor.delete_note', contract_id=contract.id, stage_id=action.contract_stage_id, note_id=action.id) }}"<i class="fa fa-trash-o"></i></a>
    </span>
    {% endif %}
  </div>

  {# update #}
  {%- elif action.action_type == 'update' -%}
  <div class="action-event js-filter-action-update">
    <span class="event-icon"><i class="fa fa-envelope-o"></i></span>
    {{ pn.print_name(action, current_user) }}
    sent <strong>{{ action.action_detail.sent_to }}</strong> an update on {{ action.taken_at|datetimeformat('%m/%d/%y') }} with the subject "<strong>{{ action.action_detail.subject }}</strong>"{% if action.action_detail.attachments and action.action_detail.attachments|length > 0 %} and {{ action.action_detail.attachments|length }} attachment(s){% endif -%}.
  </div>

  {# opportunity #}
  {%- elif action.action_type == 'post' -%}
  <div class="action-event js-filter-action-post">
    <span class="event-icon"><i class="fa fa-bullhorn"></i></span>
    {{ pn.print_name(action, current_user) }}
    {{ action.action_detail.label }} the {{ action.action_detail.title }} opportunity on {{ action.taken_at|datetimeformat('%m/%d/%y') }}. View it <a href="{{ url_for('opportunities.detail', opportunity_id=action.action_detail.opportunity_id) }}">on Beacon</a>.
  </div>

  {# date handling #}
  {%- elif action.action_type == 'entered' -%}
  <div class="action-event action-event-date js-filter-action-stage">
    <span class="event-icon"><i class="fa fa-circle-o"></i></span>
    {{ pn.print_name(action, current_user) }} started work on "<strong>{{ action.action_detail.stage_name }}</strong>" on {{ action.action_detail.timestamp|datetimeformat('%m/%d/%y') }} (action taken on {{ action.taken_at|datetimeformat('%m/%d/%y') }}).
  </div>

  {%- elif action.action_type == 'exited' and action.action_detail -%}
  <div class="action-event action-event-date js-filter-action-stage">
    <span class="event-icon"><i class="fa fa-check-circle"></i></span>
    {{ pn.print_name(action, current_user) }} completed work on "<strong>{{ action.action_detail.stage_name }}</strong>" on {{ action.action_detail.timestamp|datetimeformat('%m/%d/%y') }} (action taken on {{ action.taken_at|datetimeformat('%m/%d/%y') }}).
  </div>

  {%- elif action.action_type == 'reversion' -%}
  <div class="action-event action-event-date js-filter-action-stage">
    <span class="event-icon"><i class="fa fa-repeat"></i></span>
    {{ action.action_detail.label }} on "<strong>{{ action.action_detail.stage_name }}</strong>" on {{ action.action_detail.timestamp|datetimeformat('%m/%d/%y') }} (action taken on {{ action.taken_at|datetimeformat('%m/%d/%y') }}).
  </div>

  {# metadata update handling #}
  {%- elif action.action_type == 'update-metadata' -%}
  <div class="action-event js-filter-action-metadata">
    <span class="event-icon"><i class="fa fa-file-text-o"></i></span>
    {{ pn.print_name(action, current_user) }} set
    {% for field, value in action['action_detail'].items() if value is not none %}
      {{ field.replace('_', ' ')|title }} to "{{ value }}"
      {{- csl.comma_separated_loop(loop) -}}
    {% endfor %}
    on {{ action.taken_at|datetimeformat('%m/%d/%y') }}
  </div>

  {# flow switch handling #}
  {%- elif action.action_type == 'flow_switch' -%}
  <div class="action-event js-filter-action-flow-switch">
    <span class="event-icon"><i class="fa fa-exchange"></i></span>
    {{ pn.print_name(action, current_user) }}
    switched the contract flow from "{{ action.action_detail.old_flow }}" to "{{ action.action_detail.new_flow }}". Here is the action log from the previous work:
    {% for _action in action.action_detail.old_flow_actions %}
      {{ render_activity_log(_action, current_user, contract, false) }}
    {% endfor %}
  </div>

  {# extension handling #}
  {%- elif action.action_type == 'extension' -%}
  <div class="action-event js-filter-action-extension">
    <span class="event-icon"><i class="fa fa-arrows-h"></i></span>
    {{ pn.print_name(action, current_user) }}
    extended the contract on {{ action.taken_at|datetimeformat('%m/%d/%y') }}.
  </div>

  {%- endif -%}

{% endmacro %}

purchasing/templates/macros/render_alert.html
{% macro render_alert(category, message) %}
  <div class="alert {{ category }} alert-dismissible flashed-alert fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
  </div>
{% endmacro %}

purchasing/templates/macros/render_pagination.html
{% macro render_pagination(pagination, pagination_class) %}
  {% if pagination.has_prev %}
    <a href="{{ url_for_other_page(pagination.page - 1)}}">&laquo; Prev</a>
  {% endif %}
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <a href="{{ url_for_other_page(page) }}">{{ page }}</a>
      {% else %}
        <strong>{{ page }}</strong>
      {% endif %}
    {% else %}
      <span class=ellipsis>…</span>
    {% endif %}
  {%- endfor %}
  {% if pagination.has_next %}
    <a href="{{ url_for_other_page(pagination.page + 1)}}">Next &raquo;</a>
  {% endif %}
{% endmacro %}

purchasing/templates/macros/with_errors.html
{% macro with_errors(field) %}
  {% if field.errors %}
    {% set css_class = 'has-error ' + kwargs.pop('class_', '') %}
    {% for error in field.errors %}
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <span>{{ error|e }}</span>
    </div>
    {% endfor %}
    {{ field(class=css_class, **kwargs) }}
  {% else %}
    {{ field(**kwargs) }}
  {% endif %}
{% endmacro %}